### ISSUE TITLE
Auto dark mode detection

### ISSUE THREAD

**Issue by guigur** [owntech-foundation/PinMaker#1]
can be achieved with `@media (prefers-color-scheme:dark)`

``` css
<style>
	line, circle {
		stroke: black;
		fill: black;
		}
	@media (prefers-color-scheme:dark) {
		line, circle {
			stroke: white;
			fill: white
			}
		}
</style>
```
